services:
  - type: web
    plan: free
    name: FileStreamBot-pro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m Adarsh
    repo: https://github.com/Thorsaboy/FileStreamBot-pro.git      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH
        sync: false
      - key: PORT
        sync: false
      - key: OWNER_USERNAME
        sync: false
      - key: DATABASE_URI
        sync: false     
      - key: BIN_ChANNEL
        sync: false
      - key: FQDN
       sync: false
    autoDeploy: true
